#+title: Projet Principes de la Programmation 2022-2023
#+subtitle: Un gestionnaire de fenêtre fonctionnel

#+DATE:

#+OPTIONS: toc:nil lang:fr



Nous avons réalisé le projet dans son intégralité. Le projet fonctionne comme il le devrait et tous les tests sont concluants.

* Mode d'emploi

Dans un premier ouvrez un terminal puis placer vous dans le dossier contenant le logiciel,
une fois à l’intérieur effectuez la commande suivante dans le terminal : «  dune exec
ocamlwm23 ». Le logiciel se lance et ne contient aucune fenêtre à manipuler.
Voici une liste des opérations possibles et leur commande.

| Commandes                 | Signification                                                             |
|---------------------------+---------------------------------------------------------------------------|
| =h=             | permet de créer une fenêtre horizontale depuis l’emplacement de la fenêtre courante       |                                 |
| =v=                  | permet de créer une fenêtre horizontale depuis l’emplacement de la fenêtre courante      |
| =n=               | permet de déplacer le focus sur la fenêtre suivante |
| =p=   | permet de déplacer le focus sur la fenêtre precedente                           |
| =+=                  | permet d'augmenter la taille de la fenêtre courante                         |
| =-=                | permet de diminuer la taille de la fenêtre courante           |
| =r=                | permet de supprimer la fenêtre courante           |
| =q=                | permet de quitter le programme et d'afficher le nombre de fenêtres crées           |

* Implémentation

Concernant les fichiers wm.ml, color.ml et tree.ml nous avons dans un premier temps
procédé de façon graphique c’est-à-dire par des applications des différentes fonctions a des
cas particuliers afin d’en déduire la meilleure méthode pour les implémenter.
Nous avons utilisé les fonctions des 3 fichiers cité précédemment et nous avons utilisé des
monades pour encapsuler ces fonctions issues de ces fichiers.